Repository team-MUMENT/MUMENT-AOS, pull requests merged in 2022-07, with the labels that each got.

#4 [CHORE] #3 - Hilt, AutoClearedValue, Network 관련 wrapper, extension 추가
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mument_android/app/application/MumentApplication.kt
  app/src/main/java/com/mument_android/app/data/network/util/ApiResult.kt
  app/src/main/java/com/mument_android/app/di/DataSourceModule.kt
  app/src/main/java/com/mument_android/app/di/NetworkModule.kt
  app/src/main/java/com/mument_android/app/di/RepositoryModule.kt
  app/src/main/java/com/mument_android/app/di/UseCaseModule.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/util/AutoClearedValue.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: 🔎CHORE, 🎤평화🎤

#10 [CHORE] #9 add assets
  .idea/misc.xml
  app/src/main/res/drawable-hdpi/ic_filter.png
  app/src/main/res/drawable-hdpi/ic_grid_off.png
  app/src/main/res/drawable-hdpi/ic_grid_on.png
  app/src/main/res/drawable-hdpi/ic_heart_off.png
  app/src/main/res/drawable-hdpi/ic_heart_on.png
  app/src/main/res/drawable-hdpi/ic_list_off.png
  app/src/main/res/drawable-hdpi/ic_list_on.png
  app/src/main/res/drawable-hdpi/ic_logo.png
  app/src/main/res/drawable-hdpi/ic_musicnote.png
  app/src/main/res/drawable-hdpi/ic_reset.png
  app/src/main/res/drawable-hdpi/ic_search.png
  app/src/main/res/drawable-mdpi/ic_filter.png
  app/src/main/res/drawable-mdpi/ic_grid_off.png
  app/src/main/res/drawable-mdpi/ic_grid_on.png
  app/src/main/res/drawable-mdpi/ic_heart_off.png
  app/src/main/res/drawable-mdpi/ic_heart_on.png
  app/src/main/res/drawable-mdpi/ic_list_off.png
  app/src/main/res/drawable-mdpi/ic_list_on.png
  app/src/main/res/drawable-mdpi/ic_logo.png
  app/src/main/res/drawable-mdpi/ic_musicnote.png
  app/src/main/res/drawable-mdpi/ic_reset.png
  app/src/main/res/drawable-mdpi/ic_search.png
  app/src/main/res/drawable-xhdpi/ic_filter.png
  app/src/main/res/drawable-xhdpi/ic_grid_off.png
  app/src/main/res/drawable-xhdpi/ic_grid_on.png
  app/src/main/res/drawable-xhdpi/ic_heart_off.png
  app/src/main/res/drawable-xhdpi/ic_heart_on.png
  app/src/main/res/drawable-xhdpi/ic_list_off.png
  app/src/main/res/drawable-xhdpi/ic_list_on.png
  app/src/main/res/drawable-xhdpi/ic_logo.png
  app/src/main/res/drawable-xhdpi/ic_musicnote.png
  app/src/main/res/drawable-xhdpi/ic_reset.png
  app/src/main/res/drawable-xhdpi/ic_search.png
  app/src/main/res/drawable-xxhdpi/ic_filter.png
  app/src/main/res/drawable-xxhdpi/ic_grid_off.png
  app/src/main/res/drawable-xxhdpi/ic_grid_on.png
  app/src/main/res/drawable-xxhdpi/ic_heart_off.png
  app/src/main/res/drawable-xxhdpi/ic_heart_on.png
  app/src/main/res/drawable-xxhdpi/ic_list_off.png
  app/src/main/res/drawable-xxhdpi/ic_list_on.png
  app/src/main/res/drawable-xxhdpi/ic_logo.png
  app/src/main/res/drawable-xxhdpi/ic_musicnote.png
  app/src/main/res/drawable-xxhdpi/ic_reset.png
  app/src/main/res/drawable-xxhdpi/ic_search.png
  app/src/main/res/drawable-xxxhdpi/ic_filter.png
  app/src/main/res/drawable-xxxhdpi/ic_grid_off.png
  app/src/main/res/drawable-xxxhdpi/ic_grid_on.png
  app/src/main/res/drawable-xxxhdpi/ic_heart_off.png
  app/src/main/res/drawable-xxxhdpi/ic_heart_on.png
  app/src/main/res/drawable-xxxhdpi/ic_list_off.png
  app/src/main/res/drawable-xxxhdpi/ic_list_on.png
  app/src/main/res/drawable-xxxhdpi/ic_logo.png
  app/src/main/res/drawable-xxxhdpi/ic_musicnote.png
  app/src/main/res/drawable-xxxhdpi/ic_reset.png
  app/src/main/res/drawable-xxxhdpi/ic_search.png
  app/src/main/res/values/colors.xml
Labels: 🔎CHORE, 📯혜빈📯

#11 [FEAT] #9 - add logo changed
  app/src/main/res/drawable-hdpi/ic_banner.png
  app/src/main/res/drawable-hdpi/ic_logo.png
  app/src/main/res/drawable-mdpi/ic_banner.png
  app/src/main/res/drawable-mdpi/ic_logo.png
  app/src/main/res/drawable-xhdpi/ic_banner.png
  app/src/main/res/drawable-xhdpi/ic_logo.png
  app/src/main/res/drawable-xxhdpi/ic_banner.png
  app/src/main/res/drawable-xxhdpi/ic_logo.png
  app/src/main/res/drawable-xxxhdpi/ic_banner.png
  app/src/main/res/drawable-xxxhdpi/ic_logo.png
Labels: 🔎CHORE, 📯혜빈📯

#18 [Chore] Error Fix
  app/src/main/res/values/themes.xml
Labels: 🔎CHORE, 🪕민호🪕

#19 Feature/12 tag enum
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mument_android/app/application/MumentApplication.kt
  app/src/main/java/com/mument_android/app/data/enumtype/EmotionalTag.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/res/font/noto_sans.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: 🛠FEAT, 🎤평화🎤

#21 [Chore] #16 recycle view layout Create
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mument_android/app/domain/entity/MumentCard.kt
  app/src/main/java/com/mument_android/app/domain/entity/MumentCardData/Music.kt
  app/src/main/java/com/mument_android/app/domain/entity/MumentCardData/User.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
  app/src/main/res/drawable/shape_border_default_redius_11dp.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/mument_layout_cardview.xml
Labels: 🔎CHORE, 🪕민호🪕

#29 [DOCS] #27 - add readme
  README.md
Labels: 📑DOCS, 📯혜빈📯

#28 [FEAT] #25 EmotionalTagTextView, EmotionalTagCheckBox 제작
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/presentation/ui/customview/EmotionalTagCheckBox.kt
  app/src/main/java/com/mument_android/app/presentation/ui/customview/EmotionalTagTextView.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detailcontents/MumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detailcontents/MumentDetailViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
  app/src/main/java/com/mument_android/app/util/ViewUtils.kt
  app/src/main/res/drawable/rectangle_fill_blue3_20dp.xml
  app/src/main/res/drawable/rectangle_fill_gray5_20dp.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mument_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 🛠FEAT, 🎤평화🎤

#24 [ CHORE] #23 Recyclerview layout 생성
  .idea/git_toolbox_prj.xml
  .idea/kotlinScripting.xml
  app/src/main/java/com/mument_android/app/data/network/home/adapter/HeardMumentListAdapter.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/ImpressiveEmotionListAdapter.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
  app/src/main/java/com/mument_android/app/util/GlobalDiffCallBack.kt
  app/src/main/res/layout/item_heard_mument_layout.xml
  app/src/main/res/layout/item_impressive_emotion_mument_layout.xml
  app/src/main/res/layout/mument_layout_cardview.xml
Labels: 🔎CHORE, 🪕민호🪕

#31 [Feat] #30 홈 뷰 구현
  app/src/main/java/com/mument_android/app/data/network/home/adapter/BannerListAdapter.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/HeardMumentListAdapter.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/ImpressiveEmotionListAdapter.kt
  app/src/main/java/com/mument_android/app/domain/entity/TempBannerData.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
  app/src/main/res/drawable/rectangle_fill_black1_transperant_27.xml
  app/src/main/res/drawable/rectangle_fill_gray5_11dp.xml
  app/src/main/res/drawable/rectangle_fill_purple2_20dp.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_banner_layout.xml
  app/src/main/res/layout/item_heard_mument_layout.xml
  app/src/main/res/layout/item_impressive_emotion_mument_layout.xml
  app/src/main/res/layout/mument_layout_cardview.xml
  app/src/main/res/values/colors.xml
Labels: 🛠FEAT, 🪕민호🪕

#33 Feat/20 record view layout
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordTagAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecodeViewModel.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
  app/src/main/res/color/selector_color_gray1_to_purple1.xml
  app/src/main/res/color/selector_color_gray1_to_purple1_selected.xml
  app/src/main/res/drawable/oval_fill_white.xml
  app/src/main/res/drawable/rectangle_fill_blue1_14dp.xml
  app/src/main/res/drawable/rectangle_fill_purple_11dp.xml
  app/src/main/res/drawable/retangle_fill_gray3_14dp.xml
  app/src/main/res/drawable/retangle_fill_gray5_11dp.xml
  app/src/main/res/drawable/retangle_fill_purple2_11dp.xml
  app/src/main/res/drawable/selector_record_switch.xml
  app/src/main/res/drawable/selector_retangle_gray5_to_purple2.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_emotional_tag.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: 🛠FEAT, 🎹진실🎹

#44 Feature/37 like mument
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/mument_android/app/application/MumentApplication.kt
  app/src/main/java/com/mument_android/app/presentation/ui/customview/EmotionalTagCheckBox.kt
  app/src/main/java/com/mument_android/app/presentation/ui/customview/EmotionalTagTextView.kt
  app/src/main/java/com/mument_android/app/presentation/ui/customview/MumentTagCheckBox.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/EmotionalTagListAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/MumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/MumentTagListAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordTagAdapter.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
  app/src/main/res/color/selector_color_gray1_to_blue1.xml
  app/src/main/res/drawable/selector_tag_background_fill_20dp.xml
  app/src/main/res/layout/fragment_mument_detail.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_locker_card.xml
  app/src/main/res/layout/item_mument_string_tag.xml
  app/src/main/res/layout/item_tag_checkbox.xml
  app/src/main/res/layout/mument_layout_cardview.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/kotlin/Versions.kt
Labels: 🌈REFACTOR, 🎤평화🎤

#46 [Feature] #39 검색 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mument_android/app/data/datasource/home/UserPreferencesSerializer.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/BannerListAdapter.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/HeardMumentListAdapter.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/ImpressiveEmotionListAdapter.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/SearchListAdapter.kt
  app/src/main/java/com/mument_android/app/domain/entity/SearchResultData.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/BottomSheetSearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/MusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/SearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/SearchViewModel.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
  app/src/main/proto/user_prefs.proto
  app/src/main/res/layout/fragment_music_detail.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_search_list.xml
  app/src/main/res/navigation/nav_graph_home.xml
  app/src/main/res/values/themes.xml
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: 🛠FEAT, 🪕민호🪕

#48 Feat/40 record tag checked
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/data/enumtype/EmotionalTag.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordTagAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecodeViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecordViewModel.kt
  app/src/main/java/com/mument_android/app/util/ViewUtils.kt
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_mument_string_tag.xml
  app/src/main/res/layout/item_tag_checkbox.xml
  app/src/main/res/values/strings.xml
Labels: 🛠FEAT, 🎹진실🎹

#50 [FEAT] #37 - 뮤멘트 좋아요 등록 / 취소
  app/src/main/java/com/mument_android/app/presentation/ui/detail/MumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/util/RecyclerviewItemDivider.kt
Labels: 🛠FEAT, 🎤평화🎤

#52 [Feat] #40 record tag checked
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordTagAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecordViewModel.kt
  app/src/main/java/com/mument_android/app/util/ViewUtils.kt
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/values/strings.xml
Labels: 🛠FEAT, 🎹진실🎹

#65 [Feat] #47 Room Database 세팅
  app/build.gradle.kts
  app/src/main/java/com/mument_android/app/data/datasource/home/RecentSearchListDataSource.kt
  app/src/main/java/com/mument_android/app/data/datasource/home/RecentSearchListDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/datasource/home/TodayMumentDataSource.kt
  app/src/main/java/com/mument_android/app/data/datasource/home/TodayMumentDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/datasource/home/UserPreferencesSerializer.kt
  app/src/main/java/com/mument_android/app/data/datasource/locker/LockerDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/dto/MumentCard.kt
  app/src/main/java/com/mument_android/app/data/dto/ResponseMyMumentListDto.kt
  app/src/main/java/com/mument_android/app/data/local/MumentDatabase.kt
  app/src/main/java/com/mument_android/app/data/local/converter/DateTypeConverter.kt
  app/src/main/java/com/mument_android/app/data/local/converter/IntListTypeConverter.kt
  app/src/main/java/com/mument_android/app/data/local/converter/MusicTypeConverter.kt
  app/src/main/java/com/mument_android/app/data/local/converter/UserTypeConverter.kt
  app/src/main/java/com/mument_android/app/data/local/recentlist/RecentSearchDAO.kt
  app/src/main/java/com/mument_android/app/data/local/recentlist/RecentSearchData.kt
  app/src/main/java/com/mument_android/app/data/local/todaymument/TodayMumentDAO.kt
  app/src/main/java/com/mument_android/app/data/local/todaymument/TodayMumentEntity.kt
  app/src/main/java/com/mument_android/app/data/local/todaymument/todaymumentdata/Music.kt
  app/src/main/java/com/mument_android/app/data/local/todaymument/todaymumentdata/User.kt
  app/src/main/java/com/mument_android/app/data/mapper/locker/LockerMapper.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/HeardMumentListAdapter.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/ImpressiveEmotionListAdapter.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/SearchListAdapter.kt
  app/src/main/java/com/mument_android/app/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/di/DataSourceModule.kt
  app/src/main/java/com/mument_android/app/di/RepositoryModule.kt
  app/src/main/java/com/mument_android/app/di/UseCaseModule.kt
  app/src/main/java/com/mument_android/app/di/ViewModelModule.kt
  app/src/main/java/com/mument_android/app/domain/entity/LockerMumentEntity.kt
  app/src/main/java/com/mument_android/app/domain/entity/MumentCard.kt
  app/src/main/java/com/mument_android/app/domain/entity/MumentCardData/User.kt
  app/src/main/java/com/mument_android/app/domain/entity/SearchResultData.kt
  app/src/main/java/com/mument_android/app/domain/entity/TestLockerMumentCard.kt
  app/src/main/java/com/mument_android/app/domain/repository/home/HomeRepository.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/CRURecentSearchListUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/CRURecentSearchListUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/DeleteRecentSearchListUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/DeleteRecentSearchListUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/HomeTestUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/TodayMumentUseCase.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/BottomSheetSearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/SearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/SearchViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentGridAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/viewmodel/LockerViewModel.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_heard_mument_layout.xml
  app/src/main/res/layout/item_impressive_emotion_mument_layout.xml
  app/src/main/res/layout/item_locker_card.xml
  app/src/main/res/layout/item_mument_image.xml
  app/src/main/res/layout/item_search_list.xml
  app/src/main/res/layout/mument_layout_cardview.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
Labels: 🛠FEAT, 🪕민호🪕

#63 [FEAT] #60 locker like mument
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/data/datasource/locker/LockerDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFilterBottomSheetFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyLikeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyMumentFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/FilterBottomSheetAdapter.kt
  app/src/main/res/drawable-hdpi/record_icn.png
  app/src/main/res/drawable-mdpi/record_icn.png
  app/src/main/res/drawable-xhdpi/record_icn.png
  app/src/main/res/drawable-xxhdpi/record_icn.png
  app/src/main/res/drawable-xxxhdpi/record_icn.png
  app/src/main/res/layout/fragment_my_like.xml
  app/src/main/res/layout/fragment_my_mument.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🛠FEAT, 📯혜빈📯

#68 [FEAT] #64 resolve bottomsheet
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/data/network/home/adapter/HistoryListAdapter.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/SearchListAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/BottomSheetSearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFilterBottomSheetFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyLikeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyMumentFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/FilterBottomSheetAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/FilterBottomSheetSelectedAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentGridAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentLinearAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerTimeAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/viewmodel/LockerViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecordViewModel.kt
  app/src/main/res/drawable-hdpi/ic_filter_off.png
  app/src/main/res/drawable-hdpi/ic_filter_on.png
  app/src/main/res/drawable-hdpi/mument_banner_1.png
  app/src/main/res/drawable-hdpi/mument_banner_2.png
  app/src/main/res/drawable-hdpi/mument_banner_3.png
  app/src/main/res/drawable-mdpi/ic_filter_off.png
  app/src/main/res/drawable-mdpi/ic_filter_on.png
  app/src/main/res/drawable-mdpi/mument_banner_1.png
  app/src/main/res/drawable-mdpi/mument_banner_2.png
  app/src/main/res/drawable-mdpi/mument_banner_3.png
  app/src/main/res/drawable-xhdpi/ic_filter_off.png
  app/src/main/res/drawable-xhdpi/ic_filter_on.png
  app/src/main/res/drawable-xhdpi/mument_banner_1.png
  app/src/main/res/drawable-xhdpi/mument_banner_2.png
  app/src/main/res/drawable-xhdpi/mument_banner_3.png
  app/src/main/res/drawable-xxhdpi/ic_filter_off.png
  app/src/main/res/drawable-xxhdpi/ic_filter_on.png
  app/src/main/res/drawable-xxhdpi/mument_banner_1.png
  app/src/main/res/drawable-xxhdpi/mument_banner_2.png
  app/src/main/res/drawable-xxhdpi/mument_banner_3.png
  app/src/main/res/drawable-xxxhdpi/ic_filter_off.png
  app/src/main/res/drawable-xxxhdpi/ic_filter_on.png
  app/src/main/res/drawable-xxxhdpi/mument_banner_1.png
  app/src/main/res/drawable-xxxhdpi/mument_banner_2.png
  app/src/main/res/drawable-xxxhdpi/mument_banner_3.png
  app/src/main/res/drawable-xxxhdpi/selector_ic_filter.xml
  app/src/main/res/layout/fragment_locker.xml
  app/src/main/res/layout/fragment_locker_filter_bottom_sheet.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_mument_filter_string_tag.xml
Labels: 🛠FEAT, 📯혜빈📯

#70 [FEAT]#67 검색, 히스토리 기능 명세서 디테일 맞추기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mument_android/app/data/local/recentlist/RecentSearchData.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/HistoryListAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/BottomSheetSearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HistoryFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/SearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/SearchViewModel.kt
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_mument_layout.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: 🛠FEAT, 🪕민호🪕

#75 Feature/73 mument detail api
  .github/workflows/mument_workflows.yml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/mument_android/app/data/datasource/detail/MumentDetailDataSource.kt
  app/src/main/java/com/mument_android/app/data/datasource/detail/MumentDetailDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/enumtype/EmotionalTag.kt
  app/src/main/java/com/mument_android/app/data/enumtype/ImpressiveTag.kt
  app/src/main/java/com/mument_android/app/data/repository/MumentDetailRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MumentDetailViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/song/SongDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/song/SongDetailMumentListAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/song/SongDetailViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecordViewModel.kt
  app/src/main/res/layout/fragment_mument_detail.xml
  app/src/main/res/layout/fragment_song_detail.xml
Labels: 🛠FEAT, 🎤평화🎤

#76 [FEAT]#66 record view api
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mument_android/app/data/controller/RecordController.kt
  app/src/main/java/com/mument_android/app/data/controller/RecordControllerImpl.kt
  app/src/main/java/com/mument_android/app/data/datasource/record/RecordDataSource.kt
  app/src/main/java/com/mument_android/app/data/datasource/record/RecordDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/dto/record/MumentIsFirstDto.kt
  app/src/main/java/com/mument_android/app/data/dto/record/MumentRecordDto.kt
  app/src/main/java/com/mument_android/app/data/dto/record/ResponseRecordMumentDto.kt
  app/src/main/java/com/mument_android/app/data/mapper/record/RecordMapper.kt
  app/src/main/java/com/mument_android/app/data/network/record/RecordApiService.kt
  app/src/main/java/com/mument_android/app/data/network/record/RecordNetwork.kt
  app/src/main/java/com/mument_android/app/data/repository/RecordRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/di/ControllerModule.kt
  app/src/main/java/com/mument_android/app/di/DataSourceModule.kt
  app/src/main/java/com/mument_android/app/di/MapperModule.kt
  app/src/main/java/com/mument_android/app/di/NetworkModule.kt
  app/src/main/java/com/mument_android/app/di/RepositoryModule.kt
  app/src/main/java/com/mument_android/app/di/UseCaseModule.kt
  app/src/main/java/com/mument_android/app/domain/entity/record/RecordIsFirstEntity.kt
  app/src/main/java/com/mument_android/app/domain/repository/record/RecordRepository.kt
  app/src/main/java/com/mument_android/app/domain/usecase/detail/FetchMumentDetailContentUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/record/IsFirstRecordMumentUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/record/IsFirstRecordMumentUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/domain/usecase/record/RecordMumentUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/record/RecordMumentUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/domain/usecase/record/RecordTestUseCase.kt
  app/src/main/java/com/mument_android/app/presentation/ui/customview/MumentDialog.kt
  app/src/main/java/com/mument_android/app/presentation/ui/customview/MumentDialogBuilder.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/BottomSheetSearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/SearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecordViewModel.kt
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_search.xml
Labels: 🛠FEAT, 🎹진실🎹

#77 [FEAT] #69 locker my mument server connection
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/data/Test.kt
  app/src/main/java/com/mument_android/app/data/datasource/locker/LockerDataSource.kt
  app/src/main/java/com/mument_android/app/data/datasource/locker/LockerDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/dto/MyMumentListDto.kt
  app/src/main/java/com/mument_android/app/data/dto/ResponseMyMumentListDto.kt
  app/src/main/java/com/mument_android/app/data/dto/locker/LockerMyMumentDto.kt
  app/src/main/java/com/mument_android/app/data/mapper/locker/LockerMapper.kt
  app/src/main/java/com/mument_android/app/data/mapper/locker/MumentLockerCardMapper.kt
  app/src/main/java/com/mument_android/app/data/network/locker/LockerApiService.kt
  app/src/main/java/com/mument_android/app/data/network/locker/LockerNetwork.kt
  app/src/main/java/com/mument_android/app/data/repository/LockerRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/di/DataSourceModule.kt
  app/src/main/java/com/mument_android/app/di/MapperModule.kt
  app/src/main/java/com/mument_android/app/di/NetworkModule.kt
  app/src/main/java/com/mument_android/app/domain/entity/locker/LockerMumentEntity.kt
  app/src/main/java/com/mument_android/app/domain/entity/locker/TestMumentCard.kt
  app/src/main/java/com/mument_android/app/domain/repository/locker/LockerRepository.kt
  app/src/main/java/com/mument_android/app/domain/usecase/locker/FetchMyMumentListUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/locker/FetchMyMumentListUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyLikeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyMumentFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentGridAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentLinearAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerTimeAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/viewmodel/LockerViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/res/layout/item_locker_card.xml
  app/src/main/res/layout/item_locker_date.xml
  app/src/main/res/layout/item_mument_image.xml
Labels: 🛠FEAT, 📯혜빈📯

#79 [FEAT] #69 - resolve conflict
  app/src/main/java/com/mument_android/app/di/DataSourceModule.kt
  app/src/main/java/com/mument_android/app/di/NetworkModule.kt
Labels: 🛠FEAT, 📯혜빈📯

#81 Feat/78 modify locker view
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/data/Test.kt
  app/src/main/java/com/mument_android/app/data/datasource/locker/LockerDataSource.kt
  app/src/main/java/com/mument_android/app/data/datasource/locker/LockerDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/network/locker/LockerApiService.kt
  app/src/main/java/com/mument_android/app/data/repository/LockerRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/domain/repository/locker/LockerRepository.kt
  app/src/main/java/com/mument_android/app/domain/usecase/locker/FetchMyMumentListUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/locker/FetchMyMumentListUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFrameFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerLikeFilterBottomSheetFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyLikeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyMumentFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/FilterBottomSheetAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/FilterBottomSheetSelectedAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentGridAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/viewmodel/LockerViewModel.kt
  app/src/main/res/layout/fragment_locker.xml
  app/src/main/res/layout/fragment_locker_like_filter_bottom_sheet.xml
  app/src/main/res/layout/fragment_my_like.xml
  app/src/main/res/layout/fragment_my_mument.xml
Labels: 🛠FEAT, 📯혜빈📯

#83 [FEAT] #66-기록하기 완료 버튼 구현 변경 및 다른 error 수정
  app/src/main/java/com/mument_android/app/presentation/ui/home/BottomSheetSearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecordViewModel.kt
  app/src/main/res/drawable/rectangle_fill_gray2_11dp.xml
  app/src/main/res/drawable/selector_rectagle_gray2_purple1_11dp.xml
  app/src/main/res/layout/fragment_record.xml
Labels: 🛠FEAT, 🎹진실🎹

#86 [FEAT] #84 홈 화면 Remote 연결 작업 했습니다
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/mument_android/app/data/datasource/home/HomeDataSource.kt
  app/src/main/java/com/mument_android/app/data/datasource/home/HomeDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/datasource/home/RemoteMumentHistoryDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/dto/home/BannerMumentDto.kt
  app/src/main/java/com/mument_android/app/data/dto/home/KnownMumentDto.kt
  app/src/main/java/com/mument_android/app/data/dto/home/RandomMumentDto.kt
  app/src/main/java/com/mument_android/app/data/dto/home/TodayMumentDto.kt
  app/src/main/java/com/mument_android/app/data/network/home/HomeService.kt
  app/src/main/java/com/mument_android/app/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/di/DataSourceModule.kt
  app/src/main/java/com/mument_android/app/di/NetworkModule.kt
  app/src/main/java/com/mument_android/app/di/RepositoryModule.kt
  app/src/main/java/com/mument_android/app/di/UseCaseModule.kt
  app/src/main/java/com/mument_android/app/di/ViewModelModule.kt
  app/src/main/java/com/mument_android/app/domain/repository/home/HomeRepository.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/GetMumentHistoryUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/SearchMusicUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/WhenHomeEnterUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/WhenHomeEnterUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HistoryFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HistoryViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/fragment_search.xml
Labels: 🛠FEAT, 🪕민호🪕

#87 [FEAT]#85 modify remote
  app/src/main/java/com/mument_android/app/data/controller/RecordModifyController.kt
  app/src/main/java/com/mument_android/app/data/controller/RecordModifyControllerImpl.kt
  app/src/main/java/com/mument_android/app/data/network/record/RecordApiService.kt
  app/src/main/java/com/mument_android/app/di/ControllerModule.kt
  app/src/main/java/com/mument_android/app/di/UseCaseModule.kt
  app/src/main/java/com/mument_android/app/domain/usecase/record/RecordModifyMumentUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/record/RecordModifyMumentUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/BottomSheetSearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/SearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/SearchViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecordViewModel.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: 🛠FEAT, 🎹진실🎹

#89 [FEAT] #82 my mument server connection
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/data/dto/locker/LockerMyMumentDto.kt
  app/src/main/java/com/mument_android/app/data/mapper/locker/MumentLockerCardMapper.kt
  app/src/main/java/com/mument_android/app/data/repository/LockerRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/domain/entity/locker/LockerMumentEntity.kt
  app/src/main/java/com/mument_android/app/domain/usecase/locker/FetchMyMumentListUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyLikeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyMumentFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/FilterBottomSheetAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/FilterBottomSheetSelectedAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/filter/LockerFilterBottomSheetFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/filter/LockerFilterViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/viewmodel/LockerViewModel.kt
  app/src/main/res/layout/fragment_locker.xml
  app/src/main/res/layout/fragment_my_like.xml
  app/src/main/res/layout/fragment_my_mument.xml
  app/src/main/res/values/strings.xml
Labels: 🛠FEAT, 📯혜빈📯

#94 Feature/51 delete mument
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/mument_android/app/data/controller/DeleteMumentController.kt
  app/src/main/java/com/mument_android/app/data/controller/DeleteMumentControllerImpl.kt
  app/src/main/java/com/mument_android/app/di/ControllerModule.kt
  app/src/main/java/com/mument_android/app/di/UseCaseModule.kt
  app/src/main/java/com/mument_android/app/domain/usecase/detail/DeleteMumentUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/detail/DeleteMumentUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MumentDetailViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/MusicDetailViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyLikeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyMumentFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentGridAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentLinearAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerTimeAdapter.kt
  app/src/main/res/layout/fragment_mument_detail.xml
  app/src/main/res/layout/fragment_music_detail.xml
  app/src/main/res/navigation/nav_graph_locker.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: 🛠FEAT, 🎤평화🎤

#96 [FEAT]#91 record modify api connect
  app/src/main/java/com/mument_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordTagAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecordViewModel.kt
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/values/strings.xml
Labels: 🛠FEAT, 🎹진실🎹

#98 [FEAT] #90 locker like server connection
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyLikeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyMumentFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentLinearAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/filter/LockerFilterBottomSheetFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/filter/LockerLikeFilterBottomSheetFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/filter/viewmodel/LockerFilterViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/viewmodel/LockerViewModel.kt
  app/src/main/res/drawable-hdpi/mument_delete_3.png
  app/src/main/res/drawable-mdpi/mument_delete_3.png
  app/src/main/res/drawable-xhdpi/mument_delete_3.png
  app/src/main/res/drawable-xxhdpi/mument_delete_3.png
  app/src/main/res/drawable-xxxhdpi/mument_delete_3.png
  app/src/main/res/layout/fragment_locker.xml
  app/src/main/res/layout/item_locker_card.xml
  app/src/main/res/layout/item_mument_string_tag.xml
Labels: 🛠FEAT, 📯혜빈📯

#100 Feature/95 qa
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/MusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/MusicDetailMumentListAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/MusicDetailViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/viewmodel/LockerViewModel.kt
  app/src/main/res/layout/fragment_mument_detail.xml
  app/src/main/res/layout/fragment_music_detail.xml
  app/src/main/res/layout/item_music_detail_list.xml
  app/src/main/res/layout/item_music_detail_mument.xml
Labels: 🛠FEAT, 🎤평화🎤

#102 [FEAT] #92 홈, 검색 관련 처리 완료
  app/src/main/java/com/mument_android/app/data/datasource/home/LocalTodayMumentDataSource.kt
  app/src/main/java/com/mument_android/app/data/datasource/home/LocalTodayMumentDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/dto/home/AgainMument.kt
  app/src/main/java/com/mument_android/app/data/dto/home/Mument.kt
  app/src/main/java/com/mument_android/app/data/dto/home/TodayMument.kt
  app/src/main/java/com/mument_android/app/data/local/MumentDatabase.kt
  app/src/main/java/com/mument_android/app/data/local/converter/MusicTypeConverter.kt
  app/src/main/java/com/mument_android/app/data/local/converter/UserTypeConverter.kt
  app/src/main/java/com/mument_android/app/data/local/todaymument/TodayMumentDAO.kt
  app/src/main/java/com/mument_android/app/data/local/todaymument/TodayMumentEntity.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/SearchListAdapter.kt
  app/src/main/java/com/mument_android/app/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/di/DataSourceModule.kt
  app/src/main/java/com/mument_android/app/di/UseCaseModule.kt
  app/src/main/java/com/mument_android/app/domain/entity/musicdetail/musicdetaildata/Music.kt
  app/src/main/java/com/mument_android/app/domain/repository/home/HomeRepository.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/SaveTodayMumentUseCase.kt
  app/src/main/java/com/mument_android/app/domain/usecase/home/SaveTodayMumentUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/BottomSheetSearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/SearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_banner_layout.xml
  app/src/main/res/layout/mument_layout_cardview.xml
Labels: 🛠FEAT, 🪕민호🪕

#104 Feature/95 qa
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/data/datasource/record/RecordDataSource.kt
  app/src/main/java/com/mument_android/app/data/datasource/record/RecordDataSourceImpl.kt
  app/src/main/java/com/mument_android/app/data/dto/detail/MusicDetailDto.kt
  app/src/main/java/com/mument_android/app/data/mapper/album/MusicWithMyMumentMapper.kt
  app/src/main/java/com/mument_android/app/data/mapper/detail/MumentCardMapper.kt
  app/src/main/java/com/mument_android/app/data/mapper/detail/MumentSummaryMapper.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/SearchListAdapter.kt
  app/src/main/java/com/mument_android/app/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/data/repository/LockerRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/data/repository/MumentDetailRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/data/repository/MumentListRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/data/repository/MusicDetailRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/data/repository/RecordRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/domain/entity/detail/MumentSummaryEntity.kt
  app/src/main/java/com/mument_android/app/domain/entity/detail/MusicWithMyMumentEntity.kt
  app/src/main/java/com/mument_android/app/domain/usecase/main/CancelLikeMumentUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/domain/usecase/main/LikeMumentUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/domain/usecase/record/RecordModifyMumentUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/domain/usecase/record/RecordMumentUseCaseImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/BaseMusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/HomeMusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/LockerMusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/MusicDetailMumentListAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/MusicDetailViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HistoryFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/MusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/SearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HistoryViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/sign/viewmodel/SignViewModel.kt
  app/src/main/res/layout/fragment_base_music_detail.xml
  app/src/main/res/layout/item_music_detail_list.xml
  app/src/main/res/layout/item_music_detail_mument.xml
  app/src/main/res/navigation/nav_graph_home.xml
  app/src/main/res/navigation/nav_graph_locker.xml
Labels: 🛠FEAT, 🎤평화🎤

#105 [FEAT] #99 reflect design qa
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/presentation/ui/customview/MumentTagCheckBox.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyLikeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyMumentFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/res/drawable-hdpi/ic_toggle_off.png
  app/src/main/res/drawable-hdpi/ic_toggle_on.png
  app/src/main/res/drawable-mdpi/ic_toggle_off.png
  app/src/main/res/drawable-mdpi/ic_toggle_on.png
  app/src/main/res/drawable-xhdpi/ic_toggle_off.png
  app/src/main/res/drawable-xhdpi/ic_toggle_on.png
  app/src/main/res/drawable-xxhdpi/ic_toggle_off.png
  app/src/main/res/drawable-xxhdpi/ic_toggle_on.png
  app/src/main/res/drawable-xxhdpi/selector_ic_toggle.xml
  app/src/main/res/drawable-xxxhdpi/ic_toggle_off.png
  app/src/main/res/drawable-xxxhdpi/ic_toggle_on.png
  app/src/main/res/layout/fragment_locker.xml
  app/src/main/res/layout/fragment_locker_filter_bottom_sheet.xml
  app/src/main/res/layout/fragment_locker_like_filter_bottom_sheet.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_locker_card.xml
  app/src/main/res/layout/item_locker_date.xml
  app/src/main/res/layout/item_mument_filter_string_tag.xml
  app/src/main/res/layout/item_mument_image.xml
  app/src/main/res/layout/item_mument_string_tag.xml
Labels: 🛠FEAT, 📯혜빈📯

#106 [FEAT] Bottom Sheet Issue Complete
  app/src/main/java/com/mument_android/app/presentation/ui/home/BottomSheetSearchFragment.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_banner_layout.xml
  app/src/main/res/layout/item_search_list.xml
  app/src/main/res/values/themes.xml
Labels: 🔎CHORE, 🪕민호🪕

#108 Feature/95 qa
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/data/network/home/adapter/BannerListAdapter.kt
  app/src/main/java/com/mument_android/app/data/network/home/adapter/HistoryListAdapter.kt
  app/src/main/java/com/mument_android/app/data/repository/MumentListRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/HomeMumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/LockerMumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MumentDetailViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/BaseMusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/ClickMumentListener.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/HomeMusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/LockerMusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/MusicDetailMumentListAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/MusicDetailViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/SearchFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/history/HistoryFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyLikeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyMumentFragment.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
  app/src/main/res/layout/fragment_base_music_detail.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_mument_detail.xml
  app/src/main/res/layout/item_music_detail_list.xml
  app/src/main/res/navigation/nav_graph_home.xml
  app/src/main/res/navigation/nav_graph_locker.xml
Labels: 🛠FEAT, 🎤평화🎤

#109 [FIX] BindingAdapter 수정
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
Labels: 🛠FEAT, 🎤평화🎤

#110 [FIX] CollapsingToolbar BindingAdapter 수정
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
Labels: 🛠FEAT, 🎤평화🎤

#113 [CHORE]#101-record,home view design modify
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/SearchFragment.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_search_list.xml
Labels: 🔎CHORE, 🎹진실🎹

#115 [FEAT] Push
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MoveMusicDetailNavigatorProvider.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MoveRecordProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/BaseMusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/HomeMusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecordViewModel.kt
  app/src/main/res/layout/item_heard_mument_layout.xml
  app/src/main/res/layout/item_mument_string_tag.xml
  app/src/main/res/layout/mument_layout_cardview.xml
  app/src/main/res/navigation/nav_graph_home.xml
Labels: 🛠FEAT, 🪕민호🪕

#117 [FEAT] Push
  app/src/main/java/com/mument_android/app/data/network/home/adapter/BannerListAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_banner_layout.xml
Labels: 🔎CHORE, 🪕민호🪕

#118 Feat/112 reflect qa
  .idea/misc.xml
  app/release/output-metadata.json
  app/src/main/java/com/mument_android/app/presentation/ui/customview/MumentTagCheckBox.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LockerFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentLinearAdapter.kt
  app/src/main/res/drawable-hdpi/mument_logo.png
  app/src/main/res/drawable-mdpi/mument_logo.png
  app/src/main/res/drawable-xhdpi/mument_logo.png
  app/src/main/res/drawable-xxhdpi/ic_android.png
  app/src/main/res/drawable-xxhdpi/mument_logo.png
  app/src/main/res/drawable-xxxhdpi/mument_logo.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_locker.xml
  app/src/main/res/layout/fragment_my_like.xml
  app/src/main/res/layout/fragment_my_mument.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_is_first_tag.xml
  app/src/main/res/layout/item_locker_card.xml
  app/src/main/res/layout/item_locker_date.xml
  app/src/main/res/layout/item_mument_filter_string_tag.xml
  app/src/main/res/layout/item_mument_image.xml
  app/src/main/res/layout/item_mument_string_tag.xml
  app/src/main/res/layout/item_music_detail_mument.xml
  app/src/main/res/layout/item_tag_checkbox.xml
Labels: 🛠FEAT, 📯혜빈📯

#119 Feature/95 qa
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/data/dto/UserDto.kt
  app/src/main/java/com/mument_android/app/data/mapper/detail/MumentCardMapper.kt
  app/src/main/java/com/mument_android/app/data/repository/MumentDetailRepositoryImpl.kt
  app/src/main/java/com/mument_android/app/di/NavigatorModule.kt
  app/src/main/java/com/mument_android/app/domain/entity/MumentCard.kt
  app/src/main/java/com/mument_android/app/domain/entity/user/UserEntity.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/HomeMumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/MumentDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/EditMumentNavigator.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/EditMumentNavigatorProvider.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/EditMumentNavigatorProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/MoveMusicDetailNavigatorProvider.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/MoveMusicDetailNavigatorProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/MoveRecordProvider.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/MoveRecordProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/BaseMusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/music/HomeMusicDetailFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/RecordFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/record/viewmodel/RecordViewModel.kt
  app/src/main/java/com/mument_android/app/util/GlobalBindingAdapter.kt
  app/src/main/res/layout/fragment_mument_detail.xml
Labels: 🛠FEAT, 🎤평화🎤

#120 [FEAT] 보관함 좋아요
  .idea/misc.xml
  app/src/main/java/com/mument_android/app/presentation/ui/locker/LikeMumentListener.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyLikeFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/MyMumentFragment.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerMumentLinearAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/adapter/LockerTimeAdapter.kt
  app/src/main/java/com/mument_android/app/presentation/ui/locker/viewmodel/LockerViewModel.kt
  app/src/main/res/layout/item_locker_card.xml
Labels: 🛠FEAT, 🎤평화🎤
