Repository team-MUMENT/MUMENT-AOS, pull requests merged in 2022-12, with the labels that each got.

#136 Feature/126 mument detail
  .github/workflows/mument_workflows.yml
  app/build.gradle.kts
  app/src/main/java/com/mument_android/app/di/NetworkAnnotation.kt
  app/src/main/java/com/mument_android/app/di/NetworkModule.kt
  app/src/main/res/navigation/nav_graph_locker.xml
  core/build.gradle.kts
  core/src/main/AndroidManifest.xml
  core/src/main/java/com/mument_android/core/util/Event.kt
  core/src/main/java/com/mument_android/core/util/SideEffect.kt
  core/src/main/java/com/mument_android/core/util/ViewState.kt
  core/src/main/res/drawable/mument_share.xml
  core/src/main/res/values/strings.xml
  core_dependent/src/main/java/com/mument_android/core_dependent/util/Extensions.kt
  core_dependent/src/main/java/com/mument_android/core_dependent/util/ViewUtils.kt
  data/build.gradle.kts
  data/src/main/java/com/mument_android/data/datasource/detail/MumentDetailDataSource.kt
  data/src/main/java/com/mument_android/data/datasource/detail/MumentDetailDataSourceImpl.kt
  data/src/main/java/com/mument_android/data/mapper/detail/MumentDetailMapper.kt
  data/src/main/java/com/mument_android/data/mapper/detail/MumentSummaryDtoMapper.kt
  data/src/main/java/com/mument_android/data/network/detail/DetailApiService.kt
  data/src/main/java/com/mument_android/data/repository/MumentDetailRepositoryImpl.kt
  domain/src/main/java/com/mument_android/domain/entity/detail/MumentDetailEntity.kt
  domain/src/main/java/com/mument_android/domain/entity/detail/MumentEntity.kt
  domain/src/main/java/com/mument_android/domain/repository/detail/MumentDetailRepository.kt
  domain/src/main/java/com/mument_android/domain/usecase/detail/FetchMumentDetailContentUseCase.kt
  domain/src/main/java/com/mument_android/domain/usecase/detail/FetchMumentDetailContentUseCaseImpl.kt
  feature/detail/build.gradle.kts
  feature/detail/src/main/java/com/mument_android/detail/mument/MumentDetailContract.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/MumentDetailFragment.kt
  feature/detail/src/main/java/com/mument_android/detail/util/GlobalBindingAdapter.kt
  feature/detail/src/main/java/com/mument_android/detail/viewmodels/MumentDetailViewModel.kt
  feature/detail/src/main/res/layout/activity_declar_mument.xml
  feature/detail/src/main/res/layout/fragment_mument_detail.xml
  feature/home/build.gradle.kts
  feature/locker/build.gradle.kts
  feature/locker/src/main/java/com/mument_android/locker/LockerNavigatorProvider.kt
  feature/locker/src/main/java/com/mument_android/locker/MyLikeFragment.kt
  feature/record/build.gradle.kts
  feature/record/src/main/java/com/mument_android/record/RecordFragment.kt
Labels: 🌈REFACTOR, 🎤평화🎤

#140 Feat/137 alarm setting
  .idea/misc.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/mument_android/mypage/fragment/AlarmSettingFragment.kt
  feature/mypage/src/main/res/drawable-hdpi/mument_toggle.webp
  feature/mypage/src/main/res/drawable-hdpi/mument_toggle_off.webp
  feature/mypage/src/main/res/drawable-mdpi/mument_toggle.webp
  feature/mypage/src/main/res/drawable-mdpi/mument_toggle_off.webp
  feature/mypage/src/main/res/drawable-xhdpi/mument_toggle.webp
  feature/mypage/src/main/res/drawable-xhdpi/mument_toggle_off.webp
  feature/mypage/src/main/res/drawable-xxhdpi/mument_toggle.webp
  feature/mypage/src/main/res/drawable-xxhdpi/mument_toggle_off.webp
  feature/mypage/src/main/res/drawable-xxxhdpi/mument_toggle.webp
  feature/mypage/src/main/res/drawable-xxxhdpi/mument_toggle_off.webp
  feature/mypage/src/main/res/drawable/selector_mypage_switch.xml
  feature/mypage/src/main/res/layout/fragment_alarm_setting.xml
  feature/mypage/src/main/res/values/strings.xml
  feature/mypage/src/main/res/xml/setting_alarm_preference.xml
Labels: 🛠FEAT, 🎹진실🎹

#145 Feature/126 mument detail
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/file_paths.xml
  core_dependent/src/main/java/com/mument_android/core_dependent/util/MediaUtils.kt
  core_dependent/src/main/java/com/mument_android/core_dependent/util/ViewUtils.kt
  core_dependent/src/main/res/anim/slide_down_dialog.xml
  core_dependent/src/main/res/anim/slide_up_dialog.xml
  core_dependent/src/main/res/drawable/mument_watermark.png
  core_dependent/src/main/res/drawable/rectangle_fill_white_11dp.xml
  core_dependent/src/main/res/values/colors.xml
  core_dependent/src/main/res/values/theme.xml
  domain/src/main/java/com/mument_android/domain/entity/detail/MumentEntity.kt
  feature/detail/build.gradle.kts
  feature/detail/src/main/java/com/mument_android/detail/mument/MumentDetailContract.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/MumentDetailFragment.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/MumentToShareDialogFragment.kt
  feature/detail/src/main/java/com/mument_android/detail/viewmodels/MumentDetailViewModel.kt
  feature/detail/src/main/res/layout/fragment_mument_detail.xml
  feature/detail/src/main/res/layout/fragment_mument_to_share_dialog.xml
  feature/detail/src/main/res/values/strings.xml
  feature/detail/src/main/res/values/theme.xml
Labels: 🛠FEAT, 🎤평화🎤

#146 Refactor/142 record inflate
  app/src/main/java/com/mument_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/res/menu/menu_bottom_navi.xml
  feature/record/src/main/AndroidManifest.xml
  feature/record/src/main/java/com/mument_android/record/RecordActivity.kt
  feature/record/src/main/res/layout/activity_record.xml
  feature/record/src/main/res/values/dimens.xml
  feature/record/src/main/res/values/strings.xml
Labels: 🌈REFACTOR, 🎹진실🎹

#148 Feature/139 event refactor
  app/src/main/AndroidManifest.xml
  feature/home/src/main/java/com/mument_android/home/HomeContract.kt
  feature/home/src/main/java/com/mument_android/home/HomeFragment.kt
  feature/home/src/main/java/com/mument_android/home/SearchActivity.kt
  feature/home/src/main/java/com/mument_android/home/SearchContract.kt
  feature/home/src/main/java/com/mument_android/home/adapters/BannerListAdapter.kt
  feature/home/src/main/java/com/mument_android/home/viewmodels/HomeViewModel.kt
  feature/home/src/main/res/layout/fragment_home.xml
  feature/home/src/main/res/layout/item_banner_layout.xml
Labels: 🌈REFACTOR, 🪕민호🪕
