Repository team-MUMENT/MUMENT-AOS, pull requests merged in 2023-03, with the labels that each got.

#243 Fix/239 navi error
  app/build.gradle.kts
  app/src/main/java/com/mument_android/app/Notification.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/MainHomeNavigatorProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/MumentDetailNavigatorProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/MusicDetailNavigatorProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/QuitMainNavigatorProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  core/src/main/java/com/mument_android/core/util/Constants.kt
  core_dependent/build.gradle.kts
  core_dependent/src/main/java/com/mument_android/core_dependent/ext/DataStoreManager.kt
  data/build.gradle.kts
  data/src/main/java/com/mument_android/data/dto/sign/KakaoDto.kt
  data/src/main/java/com/mument_android/data/mapper/sign/KakaoLoginMapper.kt
  data/src/main/java/com/mument_android/data/repository/SignRepositoryImpl.kt
  domain/src/main/java/com/mument_android/domain/entity/sign/KakaoEntity.kt
  domain/src/main/java/com/mument_android/domain/repository/sign/SignRepository.kt
  domain/src/main/java/com/mument_android/domain/usecase/sign/SignPutProfileUseCase.kt
  domain/src/main/java/com/mument_android/domain/usecase/sign/SignPutProfileUseCaseImpl.kt
  feature/detail/build.gradle.kts
  feature/detail/src/main/java/com/mument_android/detail/mument/fragment/MumentDetailFragment.kt
  feature/detail/src/main/java/com/mument_android/detail/report/SelectReportTypeDialogFragment.kt
  feature/detail/src/main/res/layout/fragment_music_detail.xml
  feature/detail/src/main/res/layout/item_music_detail_list.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/mument_android/home/main/HomeFragment.kt
  feature/home/src/main/java/com/mument_android/home/util/GlobalBindingAdapter.kt
  feature/locker/build.gradle.kts
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/mument_android/SplashActivity.kt
  feature/login/src/main/java/com/mument_android/login/LogInActivity.kt
  feature/login/src/main/java/com/mument_android/login/LogInViewModel.kt
  feature/login/src/main/java/com/mument_android/login/ProfileSettingActivity.kt
  feature/login/src/main/java/com/mument_android/onboarding/OnBoardingActivity.kt
  feature/login/src/main/java/com/mument_android/onboarding/OnBoardingFirstFragment.kt
  feature/login/src/main/java/com/mument_android/onboarding/OnBoardingSecondFragment.kt
  feature/login/src/main/java/com/mument_android/onboarding/OnBoardingThirdFragment.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/java/com/mument_android/mypage/MyPageActivity.kt
  feature/mypage/src/main/java/com/mument_android/mypage/MyPageViewModel.kt
  feature/record/build.gradle.kts
  navigation/build.gradle.kts
Labels: 🪕민호🪕, 🔥HOTFIX

#244 Feat/242 last qa
  feature/detail/src/main/java/com/mument_android/detail/mument/activity/DeclarMumentActivity.kt
  feature/detail/src/main/res/layout/activity_declar_mument.xml
  feature/detail/src/main/res/values/dimens.xml
  feature/locker/src/main/java/com/mument_android/locker/filter/LockerFilterBottomSheetFragment.kt
  feature/locker/src/main/res/layout/fragment_locker_filter_bottom_sheet.xml
  feature/login/src/main/java/com/mument_android/login/ProfileSettingActivity.kt
  feature/login/src/main/res/drawable-hdpi/mument_profile_default_image.png
  feature/login/src/main/res/drawable-mdpi/mument_profile_default_image.png
  feature/login/src/main/res/drawable-xhdpi/mument_profile_default_image.png
  feature/login/src/main/res/drawable-xxhdpi/mument_profile_default_image.png
  feature/login/src/main/res/drawable-xxxhdpi/mument_profile_default_image.png
  feature/login/src/main/res/layout/activity_profile_setting.xml
  feature/mypage/src/main/res/drawable-hdpi/mument_profile_camera.webp
  feature/mypage/src/main/res/drawable-mdpi/mument_profile_camera.webp
  feature/mypage/src/main/res/drawable-xhdpi/mument_profile_camera.webp
  feature/mypage/src/main/res/drawable-xxhdpi/mument_profile_camera.webp
  feature/mypage/src/main/res/drawable-xxxhdpi/mument_profile_camera.webp
  feature/mypage/src/main/res/layout/fragment_alarm_setting.xml
  feature/mypage/src/main/res/layout/fragment_unregister.xml
Labels: 🛠FEAT, 🎹진실🎹

#249 Chore/248 optimization inflate
  data/src/main/java/com/mument_android/data/network/AuthInterceptor.kt
  feature/locker/src/main/java/com/mument_android/locker/LockerFragment.kt
  feature/locker/src/main/java/com/mument_android/locker/MyLikeFragment.kt
  feature/locker/src/main/java/com/mument_android/locker/MyMumentFragment.kt
  feature/locker/src/main/java/com/mument_android/locker/adapters/LockerMumentLinearAdapter.kt
  feature/locker/src/main/java/com/mument_android/locker/adapters/LockerTimeAdapter.kt
  feature/locker/src/main/java/com/mument_android/locker/viewmodels/LockerViewModel.kt
  feature/locker/src/main/res/layout/fragment_my_like.xml
  feature/locker/src/main/res/layout/fragment_my_mument.xml
  feature/locker/src/main/res/layout/item_locker_date.xml
  feature/login/src/main/java/com/mument_android/SplashActivity.kt
  feature/login/src/main/java/com/mument_android/login/LogInActivity.kt
Labels: 🔎CHORE, 🪕민호🪕

#245 Feat/236 add ga
  .idea/compiler.xml
  app/build.gradle.kts
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/HistoryNavigatorProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core_dependent/build.gradle.kts
  core_dependent/src/main/java/com/mument_android/core_dependent/util/FirebaseAnalyticsUtil.kt
  feature/detail/build.gradle.kts
  feature/detail/src/main/AndroidManifest.xml
  feature/detail/src/main/java/com/mument_android/detail/history/HistoryListAdapter.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/activity/DeclarMumentActivity.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/fragment/MumentDetailFragment.kt
  feature/detail/src/main/java/com/mument_android/detail/music/MusicDetailMumentHeaderAdapter.kt
  feature/detail/src/main/java/com/mument_android/detail/music/MusicDetailMumentListAdapter.kt
  feature/detail/src/main/java/com/mument_android/detail/util/SuggestionNotifyAccessDialogFragment.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/mument_android/home/adapters/BannerListAdapter.kt
  feature/home/src/main/java/com/mument_android/home/adapters/HeardMumentListAdapter.kt
  feature/home/src/main/java/com/mument_android/home/adapters/ImpressiveEmotionListAdapter.kt
  feature/home/src/main/java/com/mument_android/home/main/HomeFragment.kt
  feature/locker/build.gradle.kts
  feature/locker/src/main/java/com/mument_android/locker/LockerFragment.kt
  feature/locker/src/main/java/com/mument_android/locker/MyLikeFragment.kt
  feature/locker/src/main/java/com/mument_android/locker/MyMumentFragment.kt
  feature/locker/src/main/java/com/mument_android/locker/adapters/LockerMumentGridAdapter.kt
  feature/locker/src/main/java/com/mument_android/locker/adapters/LockerMumentLinearAdapter.kt
  feature/locker/src/main/java/com/mument_android/locker/adapters/LockerTimeAdapter.kt
  feature/locker/src/main/java/com/mument_android/locker/filter/LockerFilterBottomSheetFragment.kt
  feature/locker/src/main/java/com/mument_android/locker/filter/LockerLikeFilterBottomSheetFragment.kt
  feature/locker/src/main/java/com/mument_android/locker/viewmodels/LockerViewModel.kt
  feature/login/build.gradle.kts
  feature/login/src/main/AndroidManifest.xml
  feature/login/src/main/java/com/mument_android/SplashActivity.kt
  feature/login/src/main/java/com/mument_android/login/LogInActivity.kt
  feature/login/src/main/java/com/mument_android/login/LogInViewModel.kt
  feature/login/src/main/java/com/mument_android/login/ProfileSettingActivity.kt
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/AndroidManifest.xml
  feature/mypage/src/main/java/com/mument_android/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/mument_android/mypage/fragment/AlarmSettingFragment.kt
  feature/record/build.gradle.kts
  feature/record/src/main/java/com/mument_android/record/RecordActivity.kt
Labels: 🛠FEAT, 📯혜빈📯

#250 [HOTFIX] 오류 해결
  feature/locker/src/main/java/com/mument_android/locker/MyLikeFragment.kt
  feature/locker/src/main/java/com/mument_android/locker/MyMumentFragment.kt
  feature/locker/src/main/java/com/mument_android/locker/adapters/LockerTimeAdapter.kt
  feature/login/src/main/java/com/mument_android/SplashActivity.kt
Labels: 🐞FIX, 📯혜빈📯

#253 Feat/252 user quit
  app/src/main/java/com/mument_android/app/di/MapperModule.kt
  app/src/main/java/com/mument_android/app/di/RepositoryModule.kt
  core_dependent/src/main/java/com/mument_android/core_dependent/ext/DataStoreManager.kt
  data/src/main/java/com/mument_android/data/datasource/mypage/UnregisterDataSource.kt
  data/src/main/java/com/mument_android/data/datasource/mypage/UnregisterDataSourceImpl.kt
  data/src/main/java/com/mument_android/data/dto/mypage/RequestUnregisterDto.kt
  data/src/main/java/com/mument_android/data/mapper/mypage/RequestUnregisterMapper.kt
  data/src/main/java/com/mument_android/data/network/mypage/MyPageApiService.kt
  data/src/main/java/com/mument_android/data/repository/mypage/UnregisterRepositoryImpl.kt
  domain/src/main/java/com/mument_android/domain/entity/mypage/RequestUnregisterEntity.kt
  domain/src/main/java/com/mument_android/domain/repository/mypage/UnregisterRepository.kt
  domain/src/main/java/com/mument_android/domain/usecase/mypage/FetchUnregisterInfoUseCase.kt
  domain/src/main/java/com/mument_android/domain/usecase/mypage/FetchUnregisterInfoUseCaseImpl.kt
  feature/locker/src/main/java/com/mument_android/locker/LockerFragment.kt
  feature/login/build.gradle.kts
  feature/login/src/main/AndroidManifest.xml
  feature/login/src/main/java/com/mument_android/login/LogInActivity.kt
  feature/mypage/src/main/java/com/mument_android/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/mument_android/mypage/fragment/UnregisterFragment.kt
Labels: 🛠FEAT, 📯혜빈📯

#255 Feat/254 admin branch
  app/google-services.json
  app/src/main/java/com/mument_android/app/di/RepositoryModule.kt
  core_dependent/src/main/java/com/mument_android/core_dependent/ext/DataStoreManager.kt
  data/src/main/java/com/mument_android/data/datasource/home/HomeDataSource.kt
  data/src/main/java/com/mument_android/data/datasource/home/HomeDataSourceImpl.kt
  data/src/main/java/com/mument_android/data/dto/detail/Exist.kt
  data/src/main/java/com/mument_android/data/dto/home/Exist.kt
  data/src/main/java/com/mument_android/data/repository/HomeRepositoryImpl.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/fragment/MumentDetailFragment.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/viewmodel/MumentDetailViewModel.kt
  feature/detail/src/main/res/layout/fragment_mument_detail.xml
  feature/login/src/main/java/com/mument_android/SplashActivity.kt
  feature/login/src/main/java/com/mument_android/login/LogInActivity.kt
  feature/login/src/main/java/com/mument_android/login/LogInViewModel.kt
Labels: 🛠FEAT, 🪕민호🪕

#258 Feat/256 modify ga
  app/src/main/java/com/mument_android/app/presentation/ui/main/viewmodel/MainViewModel.kt
  core_dependent/src/main/java/com/mument_android/core_dependent/util/FirebaseAnalyticsUtil.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/viewmodel/MumentDetailViewModel.kt
  feature/login/src/main/AndroidManifest.xml
  feature/login/src/main/java/com/mument_android/login/util/GalleryUtil.kt
  feature/record/src/main/java/com/mument_android/record/RecordActivity.kt
Labels: 🛠FEAT, 📯혜빈📯

#261 Hotfix/release fix
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/com/mument_android/app/application/MumentApplication.kt
  app/src/main/java/com/mument_android/app/presentation/RestrictUserDialog.kt
  feature/login/src/main/AndroidManifest.xml
  feature/login/src/main/java/com/mument_android/ApplicationClass.kt
  feature/login/src/main/java/com/mument_android/login/LogInActivity.kt
  feature/mypage/src/main/java/com/mument_android/mypage/MyPageActivity.kt
Labels: 🪕민호🪕, 🔥HOTFIX

#262 Hotfix/release fix
  .gitignore
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/com/mument_android/app/application/MumentApplication.kt
  app/src/main/java/com/mument_android/app/di/AppModule.kt
  app/src/main/java/com/mument_android/app/di/NavigatorModule.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/MoveFromHistoryToDetailImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/MusicDetailNavigatorProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/detail/mument/navigator/StackProviderImpl.kt
  app/src/main/java/com/mument_android/app/presentation/ui/main/MainActivity.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core/proguard-rules.pro
  core/src/main/java/com/mument_android/core/util/Constants.kt
  core_dependent/proguard-rules.pro
  core_dependent/src/main/java/com/mument_android/core_dependent/util/ViewUtils.kt
  data/build.gradle.kts
  data/proguard-rules.pro
  data/src/main/java/com/mument_android/data/dto/UserDto.kt
  data/src/main/java/com/mument_android/data/dto/home/NotifyItem.kt
  data/src/main/java/com/mument_android/data/dto/home/TodayItem.kt
  data/src/main/java/com/mument_android/data/dto/record/MumentModifyDto.kt
  data/src/main/java/com/mument_android/data/repository/HomeRepositoryImpl.kt
  domain/proguard-rules.pro
  domain/src/main/java/com/mument_android/domain/entity/User.kt
  domain/src/main/java/com/mument_android/domain/entity/detail/MusicReqeust.kt
  domain/src/main/java/com/mument_android/domain/entity/history/MusicX.kt
  domain/src/main/java/com/mument_android/domain/entity/home/BannerEntity.kt
  domain/src/main/java/com/mument_android/domain/entity/home/Like.kt
  domain/src/main/java/com/mument_android/domain/entity/home/Notice.kt
  domain/src/main/java/com/mument_android/domain/entity/home/RecentSearchData.kt
  domain/src/main/java/com/mument_android/domain/entity/music/MusicInfoEntity.kt
  domain/src/main/java/com/mument_android/domain/entity/musicdetail/musicdetaildata/Music.kt
  domain/src/main/java/com/mument_android/domain/entity/record/MumentModifyEntity.kt
  domain/src/main/java/com/mument_android/domain/entity/user/UserEntity.kt
  feature/detail/src/main/java/com/mument_android/detail/history/HistoryActivity.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/fragment/MumentDetailFragment.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/listener/StackProvider.kt
  feature/detail/src/main/java/com/mument_android/detail/mument/viewmodel/MumentReportViewModel.kt
  feature/detail/src/main/java/com/mument_android/detail/music/MusicDetailFragment.kt
  feature/detail/src/main/java/com/mument_android/detail/music/MusicDetailViewModel.kt
  feature/home/src/main/java/com/mument_android/home/main/HomeFragment.kt
  feature/login/src/main/java/com/mument_android/SplashActivity.kt
  feature/login/src/main/java/com/mument_android/login/util/MultipartResolver.kt
  feature/mypage/src/main/java/com/mument_android/mypage/data/NoticeData.kt
  feature/record/src/main/java/com/mument_android/record/RecordActivity.kt
  gradle/wrapper/gradle-wrapper.properties
  navigation/src/main/java/com/angdroid/navigation/MoveFromHistoryToDetail.kt
  navigation/src/main/java/com/angdroid/navigation/StackProvider.kt
Labels: 🐞FIX, 🪕민호🪕

#263 [FIX] Class Not Cast Fix
  app/proguard-rules.pro
  data/proguard-rules.pro
  domain/proguard-rules.pro
Labels: 🪕민호🪕, 🔥HOTFIX

#265 Fix/264 modify qa
  .idea/compiler.xml
  feature/login/src/main/res/values/strings.xml
  feature/mypage/src/main/java/com/mument_android/mypage/MyPageActivity.kt
  feature/mypage/src/main/java/com/mument_android/mypage/MyPageViewModel.kt
Labels: 🐞FIX, 📯혜빈📯
